# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

TimeHoursCalCpp1 <- function(x) {
    .Call('_TimeUseR_TimeHoursCalCpp1', PACKAGE = 'TimeUseR', x)
}

TimeHoursCalCpp2 <- function(x) {
    .Call('_TimeUseR_TimeHoursCalCpp2', PACKAGE = 'TimeUseR', x)
}

TimeHoursCalCpp3 <- function(x) {
    .Call('_TimeUseR_TimeHoursCalCpp3', PACKAGE = 'TimeUseR', x)
}

TimeHoursCalCpp4 <- function(x) {
    .Call('_TimeUseR_TimeHoursCalCpp4', PACKAGE = 'TimeUseR', x)
}

rcpp_hello <- function() {
    .Call('_TimeUseR_rcpp_hello', PACKAGE = 'TimeUseR')
}

Signif <- function(x) {
    .Call('_TimeUseR_Signif', PACKAGE = 'TimeUseR', x)
}

